In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from xgboost import XGBRegressor

In [3]:
df = pd.read_csv("logistics_dataset.csv")

In [4]:
df

,item_id,category,stock_level,reorder_point,reorder_frequency_days,lead_time_days,daily_demand,demand_std_dev,item_popularity_score,storage_location_id,...,unit_price,holding_cost_per_unit_day,stockout_count_last_month,order_fulfillment_rate,total_orders_last_month,turnover_ratio,layout_efficiency_score,last_restock_date,forecasted_demand_next_7d,KPI_score
0,ITM10000,Pharma,283,21,4,4,49.85,1.56,0.43,L82,...,117.80,1.14,0,0.80,700,3.33,0.33,2024-02-17,184.37,0.556
1,ITM10001,Automotive,301,52,9,6,23.34,2.55,0.69,L15,...,178.80,1.09,3,0.79,736,10.36,0.98,2024-10-01,221.94,0.723
2,ITM10002,Groceries,132,60,11,8,37.69,3.15,0.62,L4,...,54.05,0.95,7,0.75,814,14.32,0.87,2024-04-07,53.85,0.680
3,ITM10003,Automotive,346,46,13,5,33.69,2.79,0.21,L95,...,31.10,1.90,0,0.96,994,2.08,0.29,2024-01-27,92.04,0.488
4,ITM10004,Automotive,49,55,4,6,49.58,5.23,0.31,L36,...,104.97,0.63,5,0.83,299,5.65,0.96,2024-05-17,194.58,0.670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,ITM13199,Groceries,343,21,12,2,39.88,1.30,0.34,L43,...,24.63,1.50,3,0.79,87,11.80,0.20,2024-11-28,237.04,0.545
3200,ITM13200,Electronics,428,43,5,7,2.68,4.25,0.91,L83,...,79.04,1.46,4,0.77,833,14.96,0.39,2024-11-28,34.00,0.605
3201,ITM13201,Groceries,415,80,14,5,49.15,5.41,0.14,L11,...,199.89,1.11,9,0.89,937,7.63,0.60,2024-10-02,62.57,0.509
3202,ITM13202,Groceries,173,84,3,9,43.39,8.47,0.69,L58,...,65.45,1.04,4,0.86,905,6.37,0.46,2024-03-30,36.96,0.565
3203,ITM13203,Apparel,377,40,14,3,29.40,7.43,0.14,L48,...,39.88,1.94,9,0.92,812,8.74,0.54,2024-05-25,193.91,0.435

In [5]:
cols_to_drop = [
    "storage_location_id",
    "zone",
    "picking_time_seconds",
    "handling_cost_per_unit",
    "layout_efficiency_score",
    "KPI_score",
]

df.drop(columns=cols_to_drop, inplace=True, errors="ignore")

In [6]:
df

,item_id,category,stock_level,reorder_point,reorder_frequency_days,lead_time_days,daily_demand,demand_std_dev,item_popularity_score,unit_price,holding_cost_per_unit_day,stockout_count_last_month,order_fulfillment_rate,total_orders_last_month,turnover_ratio,last_restock_date,forecasted_demand_next_7d
0,ITM10000,Pharma,283,21,4,4,49.85,1.56,0.43,117.80,1.14,0,0.80,700,3.33,2024-02-17,184.37
1,ITM10001,Automotive,301,52,9,6,23.34,2.55,0.69,178.80,1.09,3,0.79,736,10.36,2024-10-01,221.94
2,ITM10002,Groceries,132,60,11,8,37.69,3.15,0.62,54.05,0.95,7,0.75,814,14.32,2024-04-07,53.85
3,ITM10003,Automotive,346,46,13,5,33.69,2.79,0.21,31.10,1.90,0,0.96,994,2.08,2024-01-27,92.04
4,ITM10004,Automotive,49,55,4,6,49.58,5.23,0.31,104.97,0.63,5,0.83,299,5.65,2024-05-17,194.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,ITM13199,Groceries,343,21,12,2,39.88,1.30,0.34,24.63,1.50,3,0.79,87,11.80,2024-11-28,237.04
3200,ITM13200,Electronics,428,43,5,7,2.68,4.25,0.91,79.04,1.46,4,0.77,833,14.96,2024-11-28,34.00
3201,ITM13201,Groceries,415,80,14,5,49.15,5.41,0.14,199.89,1.11,9,0.89,937,7.63,2024-10-02,62.57
3202,ITM13202,Groceries,173,84,3,9,43.39,8.47,0.69,65.45,1.04,4,0.86,905,6.37,2024-03-30,36.96
3203,ITM13203,Apparel,377,40,14,3,29.40,7.43,0.14,39.88,1.94,9,0.92,812,8.74,2024-05-25,193.91

In [7]:
df["last_restock_date"] = pd.to_datetime(df["last_restock_date"])

In [8]:
expiry_map = {
    "Pharma": 365,
    "Groceries": 30,
    "Automotive": 730,
    "Electronics": 540
}

df["expiry_days"] = df["category"].map(expiry_map)
df["expiry_date"] = df["last_restock_date"] + pd.to_timedelta(df["expiry_days"], unit="D")
df["days_to_expiry"] = (df["expiry_date"] - pd.Timestamp.today()).dt.days

In [9]:
df

,item_id,category,stock_level,reorder_point,reorder_frequency_days,lead_time_days,daily_demand,demand_std_dev,item_popularity_score,unit_price,holding_cost_per_unit_day,stockout_count_last_month,order_fulfillment_rate,total_orders_last_month,turnover_ratio,last_restock_date,forecasted_demand_next_7d,expiry_days,expiry_date,days_to_expiry
0,ITM10000,Pharma,283,21,4,4,49.85,1.56,0.43,117.80,1.14,0,0.80,700,3.33,2024-02-17,184.37,365.0,2025-02-16,-326.0
1,ITM10001,Automotive,301,52,9,6,23.34,2.55,0.69,178.80,1.09,3,0.79,736,10.36,2024-10-01,221.94,730.0,2026-10-01,266.0
2,ITM10002,Groceries,132,60,11,8,37.69,3.15,0.62,54.05,0.95,7,0.75,814,14.32,2024-04-07,53.85,30.0,2024-05-07,-611.0
3,ITM10003,Automotive,346,46,13,5,33.69,2.79,0.21,31.10,1.90,0,0.96,994,2.08,2024-01-27,92.04,730.0,2026-01-26,18.0
4,ITM10004,Automotive,49,55,4,6,49.58,5.23,0.31,104.97,0.63,5,0.83,299,5.65,2024-05-17,194.58,730.0,2026-05-17,129.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,ITM13199,Groceries,343,21,12,2,39.88,1.30,0.34,24.63,1.50,3,0.79,87,11.80,2024-11-28,237.04,30.0,2024-12-28,-376.0
3200,ITM13200,Electronics,428,43,5,7,2.68,4.25,0.91,79.04,1.46,4,0.77,833,14.96,2024-11-28,34.00,540.0,2026-05-22,134.0
3201,ITM13201,Groceries,415,80,14,5,49.15,5.41,0.14,199.89,1.11,9,0.89,937,7.63,2024-10-02,62.57,30.0,2024-11-01,-433.0
3202,ITM13202,Groceries,173,84,3,9,43.39,8.47,0.69,65.45,1.04,4,0.86,905,6.37,2024-03-30,36.96,30.0,2024-04-29,-619.0
3203,ITM13203,Apparel,377,40,14,3,29.40,7.43,0.14,39.88,1.94,9,0.92,812,8.74,2024-05-25,193.91,NaN,NaT,NaN

In [10]:
df["days_of_stock_left"] = df["stock_level"] / (df["daily_demand"] + 1e-5)
df["stockout_risk"] = (df["days_of_stock_left"] < df["lead_time_days"]).astype(int)

df["days_since_restock"] = (
    pd.Timestamp.today() - df["last_restock_date"]
).dt.days

In [11]:
df

,item_id,category,stock_level,reorder_point,reorder_frequency_days,lead_time_days,daily_demand,demand_std_dev,item_popularity_score,unit_price,...,total_orders_last_month,turnover_ratio,last_restock_date,forecasted_demand_next_7d,expiry_days,expiry_date,days_to_expiry,days_of_stock_left,stockout_risk,days_since_restock
0,ITM10000,Pharma,283,21,4,4,49.85,1.56,0.43,117.80,...,700,3.33,2024-02-17,184.37,365.0,2025-02-16,-326.0,5.677030,0,690
1,ITM10001,Automotive,301,52,9,6,23.34,2.55,0.69,178.80,...,736,10.36,2024-10-01,221.94,730.0,2026-10-01,266.0,12.896310,0,463
2,ITM10002,Groceries,132,60,11,8,37.69,3.15,0.62,54.05,...,814,14.32,2024-04-07,53.85,30.0,2024-05-07,-611.0,3.502254,1,640
3,ITM10003,Automotive,346,46,13,5,33.69,2.79,0.21,31.10,...,994,2.08,2024-01-27,92.04,730.0,2026-01-26,18.0,10.270107,0,711
4,ITM10004,Automotive,49,55,4,6,49.58,5.23,0.31,104.97,...,299,5.65,2024-05-17,194.58,730.0,2026-05-17,129.0,0.988302,1,600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,ITM13199,Groceries,343,21,12,2,39.88,1.30,0.34,24.63,...,87,11.80,2024-11-28,237.04,30.0,2024-12-28,-376.0,8.600800,0,405
3200,ITM13200,Electronics,428,43,5,7,2.68,4.25,0.91,79.04,...,833,14.96,2024-11-28,34.00,540.0,2026-05-22,134.0,159.700897,0,405
3201,ITM13201,Groceries,415,80,14,5,49.15,5.41,0.14,199.89,...,937,7.63,2024-10-02,62.57,30.0,2024-11-01,-433.0,8.443538,0,462
3202,ITM13202,Groceries,173,84,3,9,43.39,8.47,0.69,65.45,...,905,6.37,2024-03-30,36.96,30.0,2024-04-29,-619.0,3.987093,1,648
3203,ITM13203,Apparel,377,40,14,3,29.40,7.43,0.14,39.88,...,812,8.74,2024-05-25,193.91,NaN,NaT,NaN,12.823125,0,592

In [12]:
y = df["forecasted_demand_next_7d"]
y

0       184.37
1       221.94
2        53.85
3        92.04
4       194.58
         ...
3199    237.04
3200     34.00
3201     62.57
3202     36.96
3203    193.91
Name: forecasted_demand_next_7d, Length: 3204, dtype: float64

In [13]:
le = LabelEncoder()
df["category_encoded"] = le.fit_transform(df["category"])

In [14]:
df["is_expired"] = (df["days_to_expiry"] < 0).astype(int)

# Clip negative expiry days
df["days_to_expiry"] = df["days_to_expiry"].clip(lower=0)

In [15]:
features = [
    "category_encoded",
    "daily_demand",
    "demand_std_dev",
    "stock_level",
    "days_of_stock_left",
    "stockout_risk",
    "lead_time_days",
    "reorder_point",
    "reorder_frequency_days",
    "item_popularity_score",
    "total_orders_last_month",
    "stockout_count_last_month",
    "turnover_ratio",
    "days_since_restock",
    "days_to_expiry",
    "is_expired",
    "unit_price",
    "holding_cost_per_unit_day"
]

X = df[features]

In [16]:
X
y

0       184.37
1       221.94
2        53.85
3        92.04
4       194.58
         ...
3199    237.04
3200     34.00
3201     62.57
3202     36.96
3203    193.91
Name: forecasted_demand_next_7d, Length: 3204, dtype: float64

In [17]:
X

,category_encoded,daily_demand,demand_std_dev,stock_level,days_of_stock_left,stockout_risk,lead_time_days,reorder_point,reorder_frequency_days,item_popularity_score,total_orders_last_month,stockout_count_last_month,turnover_ratio,days_since_restock,days_to_expiry,is_expired,unit_price,holding_cost_per_unit_day
0,4,49.85,1.56,283,5.677030,0,4,21,4,0.43,700,0,3.33,690,0.0,1,117.80,1.14
1,1,23.34,2.55,301,12.896310,0,6,52,9,0.69,736,3,10.36,463,266.0,0,178.80,1.09
2,3,37.69,3.15,132,3.502254,1,8,60,11,0.62,814,7,14.32,640,0.0,1,54.05,0.95
3,1,33.69,2.79,346,10.270107,0,5,46,13,0.21,994,0,2.08,711,18.0,0,31.10,1.90
4,1,49.58,5.23,49,0.988302,1,6,55,4,0.31,299,5,5.65,600,129.0,0,104.97,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3199,3,39.88,1.30,343,8.600800,0,2,21,12,0.34,87,3,11.80,405,0.0,1,24.63,1.50
3200,2,2.68,4.25,428,159.700897,0,7,43,5,0.91,833,4,14.96,405,134.0,0,79.04,1.46
3201,3,49.15,5.41,415,8.443538,0,5,80,14,0.14,937,9,7.63,462,0.0,1,199.89,1.11
3202,3,43.39,8.47,173,3.987093,1,9,84,3,0.69,905,4,6.37,648,0.0,1,65.45,1.04
3203,0,29.40,7.43,377,12.823125,0,3,40,14,0.14,812,9,8.74,592,NaN,0,39.88,1.94

In [18]:
X = X.fillna(X.median())

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

In [20]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=600,
    learning_rate=0.03,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

XGBoostError: value -1 for Parameter max_depth should be greater equal to 0
max_depth: Maximum depth of the tree; 0 indicates no limit; a limit is required for depthwise policy

In [ ]:
!pip install xgboost

In [21]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

preds = model.predict(X_test)
preds = np.maximum(preds, 0)

mae = mean_absolute_error(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))

print("MAE :", mae)
print("RMSE:", rmse)

MAE : 75.03643103636743
RMSE: 88.56044729017191

In [23]:
y_test.mean()

151.4189391575663

In [24]:
mae/y_test.mean()

0.4955551231163008

In [25]:
preds

array([111.60334 , 130.23898 , 172.25925 , 174.82486 , 159.67546 ,
       147.08235 , 156.14581 , 157.44844 , 194.44019 , 103.49948 ,
       151.25604 , 187.42311 , 141.88747 , 111.92925 , 157.07405 ,
       172.11006 , 170.22433 , 134.26805 , 186.37796 , 161.86005 ,
       164.46129 , 141.13168 , 223.61224 , 202.96193 , 173.64217 ,
       113.20464 , 163.76678 , 172.85655 , 103.0883  , 170.74246 ,
       146.5871  , 157.67484 , 136.9333  , 177.92366 , 170.25124 ,
       121.73778 , 130.98787 , 170.3499  , 146.6501  , 197.00975 ,
       150.89496 , 178.42546 , 144.56659 , 130.17711 , 162.04721 ,
       154.84094 , 160.4573  , 154.47096 , 153.60574 , 142.45772 ,
        92.67128 , 138.61543 , 132.99748 , 143.55154 , 148.07368 ,
       140.40869 , 149.63393 , 204.22455 , 134.00208 , 149.11397 ,
       106.28466 , 155.22227 , 132.78583 , 175.10005 , 186.53293 ,
       153.59352 , 174.90324 , 167.00168 , 193.46616 , 133.30382 ,
       141.2221  , 147.14572 , 138.89339 , 168.56238 , 126.05096 ,
       144.03058 , 169.99416 , 142.33623 , 164.97957 , 150.60811 ,
       154.59178 , 162.61104 , 243.6732  , 184.74141 , 137.03223 ,
       125.697044, 109.08016 , 185.51105 , 141.86563 , 158.79024 ,
       165.73473 , 170.068   , 146.65193 , 155.43468 , 121.09612 ,
       150.9811  , 154.25143 , 150.0245  , 179.74716 , 156.48756 ,
       133.83278 , 146.42595 , 190.5288  , 135.33621 , 116.03122 ,
       153.28381 , 171.62636 , 168.99179 , 207.53625 , 149.20776 ,
       153.52693 ,  89.6441  , 153.4287  , 123.55804 , 161.25569 ,
       177.42793 , 178.85876 , 168.3728  , 171.84457 , 145.33241 ,
       172.80556 , 139.65117 , 166.57793 , 115.70223 , 146.63478 ,
       147.3867  , 146.05295 , 105.167145, 137.45639 , 126.74808 ,
       122.67696 , 180.03864 , 198.20842 , 172.33885 , 137.35057 ,
       141.80092 , 125.21425 , 154.19849 , 131.11034 , 158.73048 ,
       162.47182 , 142.14815 , 126.547935, 124.8484  , 176.6354  ,
       175.71913 , 171.83725 , 119.25539 , 102.67943 , 131.21754 ,
       102.43091 , 111.262665, 194.89417 , 121.57655 , 152.9621  ,
       157.55225 , 145.6893  , 153.30324 , 149.59352 , 133.45743 ,
       194.36404 , 156.38255 , 127.43277 , 147.44064 , 211.08215 ,
       153.90685 , 132.68352 , 205.5667  , 175.24255 , 163.8214  ,
       187.0649  , 140.9175  , 188.12247 , 156.1817  , 160.72624 ,
       135.93124 , 136.18239 , 178.90115 , 110.09796 , 121.28122 ,
       130.54669 , 156.75851 , 135.87799 , 141.2024  ,  88.74384 ,
       145.4388  , 139.68661 , 197.42944 , 150.59413 , 173.07684 ,
       171.98839 , 150.49057 , 176.51443 , 136.20438 , 173.82686 ,
       171.72867 , 173.8002  , 188.04251 , 151.32019 , 150.56526 ,
       148.95616 , 113.98975 , 111.98008 , 178.64691 , 158.62619 ,
       158.8923  , 137.53288 ,  70.96127 , 136.92732 , 152.98763 ,
       122.073265, 143.95564 , 155.55634 , 132.06026 , 158.55286 ,
       166.98877 , 181.67584 , 168.04442 , 143.2562  , 142.54309 ,
       122.63852 , 169.91295 , 114.248314, 127.715645, 167.42555 ,
       181.4325  , 135.63023 , 161.92708 , 134.94096 , 111.880516,
       138.24266 , 175.39307 , 155.45872 , 168.46371 , 170.53743 ,
       138.26918 , 129.35948 , 157.20699 , 120.99911 , 197.4408  ,
       119.386   ,  73.34297 , 180.97969 , 100.645905, 135.30971 ,
       165.69029 , 128.95058 , 126.071365, 121.6679  , 213.22333 ,
       133.60788 , 118.04709 , 194.49013 , 128.01921 , 122.34111 ,
       191.19487 , 161.95518 , 180.7443  , 181.6544  , 181.62628 ,
       158.81578 , 155.6441  , 149.56425 , 176.11966 , 134.0981  ,
       181.23466 , 174.58868 , 183.87239 , 186.88356 , 193.91498 ,
       161.84694 ,  85.57094 , 149.85529 , 164.2262  , 143.74289 ,
       133.01866 , 140.95387 , 117.1548  , 122.87502 , 174.84749 ,
       179.48454 , 156.67583 , 185.00864 , 120.547035, 216.87221 ,
       146.54582 , 130.08778 , 166.60478 , 169.13348 , 162.84163 ,
       149.54419 , 194.39948 , 117.82114 , 181.65132 , 149.86223 ,
       178.11655 , 158.93385 , 158.49153 , 151.71284 , 171.5127  ,
       129.30074 , 114.4018  , 116.43796 , 195.5517  , 177.29213 ,
       152.40656 , 150.84612 , 167.15842 , 177.71257 , 181.85648 ,
       172.6681  ,  99.97994 , 223.62608 , 161.70981 , 157.2088  ,
       173.47327 , 175.95815 , 182.69235 , 179.70808 , 161.17924 ,
       151.10123 , 106.82369 , 156.19994 , 152.17577 , 172.65416 ,
       160.98756 , 167.21133 , 170.5694  , 124.44451 , 181.26924 ,
       200.06783 , 121.968   , 139.24353 , 195.57924 , 141.74896 ,
       129.34608 , 178.3106  , 134.40865 , 129.41992 , 126.38516 ,
       146.7793  , 113.247154, 155.11095 , 182.92918 , 132.52332 ,
       181.25888 , 230.65582 , 108.19662 , 145.62494 , 153.39911 ,
       111.53517 , 179.70964 , 136.04803 ,  97.446625, 116.611374,
       154.65933 , 144.45296 , 127.40497 , 175.48888 , 182.84418 ,
       138.22392 , 177.60286 , 175.429   , 170.95444 , 131.44548 ,
       181.05307 , 177.6007  , 202.88104 , 175.86674 , 171.75026 ,
       152.55128 , 167.077   , 127.59232 , 184.62773 , 145.50612 ,
       165.99454 ,  86.481186, 175.94818 , 174.01901 , 182.52818 ,
       153.56099 , 141.59888 , 150.32701 , 147.9397  , 135.61829 ,
       158.80023 , 172.30179 , 139.18398 , 174.08862 , 167.4894  ,
       182.14104 ,  98.375725, 136.39809 , 153.16612 , 127.697174,
       155.95486 , 157.57225 , 128.43965 , 133.45125 , 182.39615 ,
       126.540855, 173.52777 , 138.82431 , 110.47601 , 123.66288 ,
       133.68307 , 144.25537 , 143.92863 , 136.74693 , 155.7193  ,
       111.61302 , 120.70882 , 120.33569 , 143.05841 , 164.01558 ,
       131.04274 , 137.53775 , 181.98862 , 124.5457  , 124.48412 ,
       170.66931 , 138.0729  , 168.84915 , 154.54825 , 163.67578 ,
       154.55354 , 189.3556  , 175.4155  , 127.431015, 143.68185 ,
       154.59657 , 111.491425, 118.42142 , 145.6656  , 166.46736 ,
       171.1082  , 134.81828 , 112.70585 , 174.72766 , 187.68336 ,
       121.10824 , 141.4508  , 153.52695 , 154.4424  , 136.66327 ,
       166.49574 , 163.5386  , 178.32677 , 170.27618 , 145.92928 ,
       157.98645 , 149.57108 , 180.30266 , 161.50874 , 200.20905 ,
       140.01715 , 145.03671 , 123.11876 , 137.5744  , 111.767914,
       210.53636 , 190.86891 , 154.06258 , 143.19348 , 188.69171 ,
       158.7766  , 153.26662 , 143.32364 , 133.52448 , 145.63492 ,
       207.06956 , 155.5845  , 148.21811 , 167.72623 , 209.1582  ,
       187.72183 , 140.84698 , 188.93648 , 164.56215 , 130.20795 ,
       168.0503  , 193.77824 , 174.7325  , 157.77191 , 140.7591  ,
       157.02657 , 168.99791 , 186.9538  , 181.83359 , 116.59986 ,
       186.49779 , 146.12747 , 112.13354 , 182.73048 , 132.10132 ,
       106.87293 , 133.46812 , 176.5311  , 191.9722  , 158.29749 ,
       149.33904 , 153.90129 , 154.89998 , 148.33615 , 137.37811 ,
       118.947655, 208.73787 , 151.51024 , 160.00238 , 167.01434 ,
       147.47878 , 145.6942  , 162.27567 , 150.83762 , 117.820885,
       141.76196 , 199.3921  ,  96.78208 , 193.27383 , 102.20297 ,
       214.72723 , 146.26897 , 176.54352 , 176.769   , 125.29575 ,
       170.53963 , 135.93393 , 158.10674 , 139.97275 , 158.49867 ,
       146.69884 , 176.00037 , 108.01835 , 152.03758 , 179.31754 ,
       189.94914 , 168.75987 , 157.02261 , 155.80304 , 164.88824 ,
       121.08421 , 139.37288 , 131.8315  , 115.04164 , 185.51154 ,
       165.19916 , 174.97264 , 185.11911 , 175.60696 , 199.32407 ,
       177.10472 , 194.86755 , 189.73622 , 146.12727 , 133.3134  ,
       162.52055 , 135.0075  , 163.02448 , 178.8468  , 167.2922  ,
       177.75996 , 166.15596 , 128.82664 , 140.5245  , 146.48393 ,
       164.79736 , 151.24963 , 164.57564 , 113.7293  , 138.92772 ,
       163.00735 , 159.73756 , 158.72092 , 161.50165 , 139.16226 ,
       180.87215 , 170.06958 , 170.77797 , 169.5563  , 186.45126 ,
       175.01167 , 158.99893 , 183.5818  , 159.42468 , 151.26683 ,
       194.55391 , 159.08197 , 179.12553 , 168.93011 , 175.7449  ,
       187.4227  , 160.28065 , 103.78724 , 177.441   , 132.49673 ,
       201.81047 , 204.04268 , 166.36583 ,  95.66636 , 139.64542 ,
       170.55176 , 127.87516 , 144.78893 , 152.96988 , 173.8876  ,
       196.43701 , 165.93901 , 153.81355 , 204.95467 , 125.65735 ,
       202.17749 , 145.78671 , 132.96997 , 180.03098 , 166.90541 ,
       180.7001  , 154.69281 , 145.79018 , 156.2765  , 113.93277 ,
       118.77465 , 181.62029 , 173.43634 , 140.16882 , 189.0212  ,
       148.68387 , 116.381905, 142.98293 , 202.99423 , 218.1332  ,
       189.40924 , 186.20747 , 162.01857 , 134.53084 , 175.11711 ,
       140.68634 , 160.34727 , 173.69386 , 107.83453 , 159.53964 ,
       134.1133  ], dtype=float32)

In [26]:
y_test

2563    131.98
2564     68.65
2565    180.19
2566    121.97
2567     67.41
         ...
3199    237.04
3200     34.00
3201     62.57
3202     36.96
3203    193.91
Name: forecasted_demand_next_7d, Length: 641, dtype: float64

In [28]:
import joblib

joblib.dump(model, "warehouse_demand_model.pkl")
joblib.dump(le, "category_encoder.pkl")   # save encoder too

['category_encoder.pkl']